### ISSUE TITLE
Use tabs in Font Settings

### ISSUE THREAD

**Issue by pathumego** [mattlag/Glyphr-Studio#192] opened 2015-05-09 15:37 UTC
A tabbed interface would make more sense here for me. 

- Glyph Proportions + Guides
- Glyph Ranges
- Metadata

**Comment by davelab6** [comment] 2015-05-10 10:33
Duplicate of https://github.com/mattlag/Glyphr-Studio/issues/187 :)

**Comment by mattlag** [comment] 2015-05-11 22:28
Closing as dupe #187

**Closed by mattlag** 2015-05-11 22:28 UTC
